fetchers:
  osmosis:
    step: 1440 # Available values : 5,15,30,60,120,240(4H),720(12H),1440(1D),10080(1W),43800(1M)
    pairs:
      - "wbtc"
      - "weth"
      - "nls"
      - "atom"
      - "statom"
      - "osmo"
      - "stosmo"

uploader:
  bucket: crypto_charts
  path: osmosis

generator:
  is-advanced: false
  
  simple:
    width: 800
    height: 400
    line-color: 14
    line-width: 2.0
    margin: 0.0
    bgr-color: "#00000000"
  
  advanced:
    # todo
