fetchers:
  bitstamp:
    limit: 800 # integer <int32> [ 1 .. 1000 ]
    step: 259200 # integer <int32> Enum: 60 180 300 900 1800 3600 7200 14400 21600 43200 86400 259200
    pairs:
      - "btcusd"
      - "btceur"
      - "btcgbp"
      - "btcpax"
      - "gbpusd"
      - "eurusd"
      - "xrpusd"
      - "xrpeur"
      - "xrpbtc"
      - "xrpgbp"
      - "ltcbtc"
      - "ltcusd"
      - "ltceur"
      - "ltcgbp"
      - "ethbtc"
      - "ethusd"
      - "etheur"
      - "ethgbp"
      - "ethpax"
      - "bchusd"
      - "bcheur"
      - "bchbtc"
      - "paxusd"
      - "xlmbtc"
      - "xlmusd"
      - "xlmeur"
      - "xlmgbp"
      - "linkusd"
      - "linkeur"
      - "linkgbp"
      - "linkbtc"
      - "usdcusd"
      - "usdceur"
      - "btcusdc"
      - "ethusdc"
      - "eth2eth"
      - "aaveusd"
      - "aaveeur"
      - "aavebtc"
      - "batusd"
      - "bateur"
      - "umausd"
      - "umaeur"
      - "daiusd"
      - "kncusd"
      - "knceur"
      - "mkrusd"
      - "mkreur"
      - "zrxusd"
      - "zrxeur"
      - "gusdusd"
      - "algousd"
      - "algoeur"
      - "algobtc"
      - "audiousd"
      - "audioeur"
      - "audiobtc"
      - "crvusd"
      - "crveur"
      - "snxusd"
      - "snxeur"
      - "uniusd"
      - "unieur"
      - "unibtc"
      - "yfiusd"
      - "yfieur"
      - "compusd"
      - "compeur"
      - "grtusd"
      - "grteur"
      - "lrcusd"
      - "lrceur"
      - "usdtusd"
      - "usdteur"
      - "usdcusdt"
      - "btcusdt"
      - "ethusdt"
      - "xrpusdt"
      - "eurteur"
      - "eurtusd"
      - "flrusd"
      - "flreur"
      - "manausd"
      - "manaeur"
      - "maticusd"
      - "maticeur"
      - "sushiusd"
      - "sushieur"
      - "chzusd"
      - "chzeur"
      - "enjusd"
      - "enjeur"
      - "hbarusd"
      - "hbareur"
      - "alphausd"
      - "alphaeur"
      - "axsusd"
      - "axseur"
      - "sandusd"
      - "sandeur"
      - "storjusd"
      - "storjeur"
      - "adausd"
      - "adaeur"
      - "adabtc"
      - "fetusd"
      - "feteur"
      - "sklusd"
      - "skleur"
      - "slpusd"
      - "slpeur"
      - "sxpusd"
      - "sxpeur"
      - "sgbusd"
      - "sgbeur"
      - "avaxusd"
      - "avaxeur"
      - "dydxusd"
      - "dydxeur"
      - "ftmusd"
      - "ftmeur"
      - "shibusd"
      - "shibeur"
      - "ampusd"
      - "ampeur"
      - "ensusd"
      - "enseur"
      - "galausd"
      - "galaeur"
      - "perpusd"
      - "perpeur"
      - "wbtcbtc"
      - "ctsiusd"
      - "ctsieur"
      - "cvxusd"
      - "cvxeur"
      - "imxusd"
      - "imxeur"
      - "nexousd"
      - "nexoeur"
      - "antusd"
      - "anteur"
      - "godsusd"
      - "godseur"
      - "radusd"
      - "radeur"
      - "bandusd"
      - "bandeur"
      - "injusd"
      - "injeur"
      - "rlyusd"
      - "rlyeur"
      - "rndrusd"
      - "rndreur"
      - "vegausd"
      - "vegaeur"
      - "1inchusd"
      - "1incheur"
      - "solusd"
      - "soleur"
      - "apeusd"
      - "apeeur"
      - "mplusd"
      - "mpleur"
      - "eurocusdc"
      - "euroceur"
      - "dotusd"
      - "doteur"
      - "nearusd"
      - "neareur"
      - "dogeusd"
      - "dogeeur"
      - "suiusd"
      - "suieur"

uploader:
  bucket: crypto_charts
  path: advanced

generator:
  is_advanced: true

  advanced:
    # todo
